namespace Birko.Xaml.Core.Theming;

/// <summary>
/// The built-in Birko themes, mirroring the four token sheets generated by Birko.DesignTokens
/// (and the Birko.Web <c>BUILTIN_THEMES</c> registry). Metadata only — a platform skin decides
/// how to realize each one.
/// </summary>
public static class BirkoThemes
{
    public const string Light = "light";
    public const string Dark = "dark";
    public const string Neon = "neon";
    public const string Finstat = "finstat";

    public static readonly ThemeInfo LightTheme = new(Light, "Light", IsDark: false, Icon: "☀");
    public static readonly ThemeInfo DarkTheme = new(Dark, "Dark", IsDark: true, Icon: "🌙");
    public static readonly ThemeInfo NeonTheme = new(Neon, "Neon", IsDark: true, Icon: "✳");
    public static readonly ThemeInfo FinstatTheme = new(Finstat, "Finstat", IsDark: false, Icon: "▦");

    /// <summary>All built-in themes, in switcher order (light first — always present).</summary>
    public static readonly IReadOnlyList<ThemeInfo> All = new[]
    {
        LightTheme, DarkTheme, NeonTheme, FinstatTheme,
    };

    public static ThemeInfo? ById(string id) => All.FirstOrDefault(t => t.Id == id);
}
